name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create a PR for release workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.1

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install NPM Dependencies
        run: pnpm install

      - name: Build the packages
        run: pnpm build:core && pnpm build:ui

      - name: Create Version PR or Publish to NPM
        id: changesets
        uses: changesets/action@v1.4.7
        with:
          commit: 'chore(release): version packages'
          title: 'chore(release): version packages'
          publish: npm run changeset publish
          version: npm run changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
